name: VPNUtils
version: '1.0.0'
main: it.mitl.vpnutils.VPNUtils
api-version: '1.21'
authors: [ Mitlit ]
description: Utilities and tools for managing how your Minecraft server interacts with VPNs.
website: dev.mitl.it
